

# This file was *autogenerated* from the file vars.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p01 = RealNumber('0.01'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_168 = Integer(168); _sage_const_167 = Integer(167)


P = BooleanPolynomialRing(names=('a0_0', 'a0_1', 'a0_2', 'a1_0', 'a1_1', 'a1_2', 'b0_0', 'b0_1', 'b0_2', 'b1_0', 'b1_1', 'b1_2', 'r0', 'r1',)); (a0_0, a0_1, a0_2, a1_0, a1_1, a1_2, b0_0, b0_1, b0_2, b1_0, b1_1, b1_2, r0, r1,) = P._first_ngens(14)


v =  (  (  (  (  ( a1_1  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b1_1  + _sage_const_1   )  + _sage_const_1   )  *  (  ( a1_0  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b1_0  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  *  (  (  ( a1_2  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b1_2  + _sage_const_1   )  + _sage_const_1   )  *  (  (  (  ( a1_1  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b1_1  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  *  (  (  ( a1_0  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b1_0  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  +  (  (  ( r0  +  ( r1  +  (  ( a1_1  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b0_1  + _sage_const_1   )  + _sage_const_1   )  )  )  *  ( r0  +  ( r1  +  (  ( a1_0  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b0_0  + _sage_const_1   )  + _sage_const_1   )  )  )  + _sage_const_1   )  *  (  ( r0  +  ( r1  +  (  ( a1_2  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b0_2  + _sage_const_1   )  + _sage_const_1   )  )  )  *  (  (  ( r0  +  ( r1  +  (  ( a1_1  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b0_1  + _sage_const_1   )  + _sage_const_1   )  )  )  + _sage_const_1   )  *  (  ( r0  +  ( r1  +  (  ( a1_0  + _sage_const_1   )  + _sage_const_1   )  *  (  ( b0_0  + _sage_const_1   )  + _sage_const_1   )  )  )  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  + _sage_const_1   )  ) 


print(v)

v1 = (  (  ( _sage_const_0   + b0_0  )  + _sage_const_1   )  *  (  ( r0  + b0_2  )  + _sage_const_1   )  + _sage_const_1   )  *  (  (  ( r0  + b0_2  )  *  ( _sage_const_0   + b0_0  )  + _sage_const_1   )  *  (  ( r0  + b0_1  )  + _sage_const_1   )  + _sage_const_1   ) 

v2 =  (  (  ( _sage_const_0   + b0_0  )  + _sage_const_1   )  *  (  ( r0  + b0_2  )  + _sage_const_1   )  + _sage_const_1   )  *  (  (  ( r0  + b0_2  )  *  ( _sage_const_0   + b0_0  )  + _sage_const_1   )  *  (  ( r0  + b0_1  )  + _sage_const_1   )  + _sage_const_1   ) 

v3 =  (  (  ( _sage_const_0   + b0_0  )  + _sage_const_1   )  *  (  ( r0  + b0_2  )  + _sage_const_1   )  + _sage_const_1   )  *  (  (  ( r0  + b0_2  )  *  ( _sage_const_0   + b0_0  )  + _sage_const_1   )  *  (  ( r0  + b0_1  )  + _sage_const_1   )  + _sage_const_1   ) 


print(v1)

print(v2)

print(v3)


f = _sage_const_0p01 
val = _sage_const_0p05 

res = _sage_const_0 
for i in range(_sage_const_1 ,_sage_const_168 ):
    res = res + val * (f) * ((_sage_const_1 -f) ** (_sage_const_167 ))
print(res)

